CREATE DATABASE member;
USE member;

CREATE TABLE user (
	userNo INTEGER UNSIGNED AUTO_INCREMENT,
    id VARCHAR(20),
    password VARCHAR(128),
    
	isAdmin BOOLEAN,
    
	name VARCHAR(20),
	nickname VARCHAR(12),
	phone VARCHAR(15),
	birthday VARCHAR(10),
	sex BOOLEAN,
	
	refreshToken VARCHAR(256),
	joinDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updateDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	
	PRIMARY KEY (userNo)
);

CREATE TABLE gameStatus (
	userNo INTEGER UNSIGNED,
	level INTEGER UNSIGNED,
	exp FLOAT,
	money INTEGER,
	
	
	PRIMARY KEY (userNo),
	FOREIGN KEY (userNo) REFERENCES user(userNo) ON UPDATE CASCADE ON DELETE CASCADE
	
);